function sval = SLP3DSelfValue(h)
% SLP3DSelfValue computes the cell-averaged 3D SLP self interaction.

arguments (Input)
    h (1, 1) double {mustBePositive};
end

arguments (Output)
    sval (1, 1) double;
end

dist = @(xx1, xx2, xx3) sqrt(xx1.^2 + xx2.^2 + xx3.^2);
s_fun = @(xx1, xx2, xx3) 1 ./ (4 * pi * dist(xx1, xx2, xx3));

sval = 0;
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    -h / 2, 0, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    -h / 2, 0, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    0, h / 2, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    0, h / 2, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    -h / 2, 0, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    -h / 2, 0, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    0, h / 2, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    0, h / 2, ...
    0, h / 2);
sval = sval / h^3;

end
