function [U, G, V] = LR_Chebyshev3D(Br, Bc, k_fun, r)

arguments (Input)
    Br Box3D;
    Bc Box3D;
    k_fun function_handle;
    r (1, 1) double;
end

arguments (Output)
    U (:, :) double;
    G (:, :) double;
    V (:, :) double;
end

rx1_points = Br.x1Points();
cx1_points = Bc.x1Points();
rx1_inter = GenerateChebyshevPoints(...
    r, ...
    Br.x1LeftPoint(),...
    Br.x1RightPoint());
cx1_inter = GenerateChebyshevPoints(...
    r, ...
    Bc.x1LeftPoint(),...
    Bc.x1RightPoint());

rx2_points = Br.x2Points();
cx2_points = Bc.x2Points();
rx2_inter = GenerateChebyshevPoints(...
    r, ...
    Br.x2LeftPoint(),...
    Br.x2RightPoint());
cx2_inter = GenerateChebyshevPoints(...
    r, ...
    Bc.x2LeftPoint(),...
    Bc.x2RightPoint());

rx3_points = Br.x3Points();
cx3_points = Bc.x3Points();
rx3_inter = GenerateChebyshevPoints(...
    r, ...
    Br.x3LeftPoint(),...
    Br.x3RightPoint());
cx3_inter = GenerateChebyshevPoints(...
    r, ...
    Bc.x3LeftPoint(),...
    Bc.x3RightPoint());

rx_inter = TensorProduct3D(rx1_inter, rx2_inter, rx3_inter);
cx_inter = TensorProduct3D(cx1_inter, cx2_inter, cx3_inter);

G = k_fun(rx_inter, cx_inter);
U1 = EvalChebyshevSm(...
    r, ...
    Br.x1LeftPoint(), ...
    Br.x1RightPoint(), ...
    rx1_points, ...
    rx1_inter);
U2 = EvalChebyshevSm(...
    r, ...
    Br.x2LeftPoint(), ...
    Br.x2RightPoint(), ...
    rx2_points, ...
    rx2_inter);
U3 = EvalChebyshevSm(...
    r, ...
    Br.x3LeftPoint(), ...
    Br.x3RightPoint(), ...
    rx3_points, ...
    rx3_inter);
V1 = EvalChebyshevSm(...
    r, ...
    Bc.x1LeftPoint(), ...
    Bc.x1RightPoint(), ...
    cx1_points, ...
    cx1_inter);
V2 = EvalChebyshevSm(...
    r, ...
    Bc.x2LeftPoint(), ...
    Bc.x2RightPoint(), ...
    cx2_points, ...
    cx2_inter);
V3 = EvalChebyshevSm(...
    r, ...
    Bc.x3LeftPoint(), ...
    Bc.x3RightPoint(), ...
    cx3_points, ...
    cx3_inter);

U = kron(U3, kron(U2, U1));
V = kron(V3, kron(V2, V1));

[U, RU] = qr(U, "econ");
[V, RV] = qr(V, "econ");
G = RU * G * RV';

end