function [a_fun, k_fun] = ExperimentKernel(n, dim, kernel_type)
% ExperimentKernel returns the diagonal and kernel functions.

arguments (Input)
    n (1, 1) double;
    dim (1, 1) double;
    kernel_type (1, 1) string;
end

arguments (Output)
    a_fun function_handle;
    k_fun function_handle;
end

a_fun = @(xx) zeros(size(xx, 1), 1);
kernel_type = string(kernel_type);

if kernel_type == "SLP"
    if dim == 2
        h = 1 / n;
        s_fun = @(xx1, xx2) -reallog(sqrt(xx1.^2 + xx2.^2)) / (2 * pi);
        sval = integral2(s_fun, -h / 2, h / 2, -h / 2, h / 2) / (h * h);
        k_fun = @(xx, yy) SLP2D(xx, yy, sval);
    elseif dim == 3
        h = 1 / n;
        sval = SLP3DSelfValue(h);
        k_fun = @(xx, yy) SLP3D(xx, yy, sval);
    else
        error("ExperimentKernel:UnsupportedDimension", ...
            "SLP experiments support dim 2 or 3.");
    end
elseif kernel_type == "OsSLP"
    kappa = 8;
    h = 1 / n;
    if dim == 2
        s_fun = @(xx1, xx2) ...
            -reallog(sqrt(xx1.^2 + xx2.^2)) / (2 * pi) ...
            .* complex(...
                cos(2 * pi * kappa * sqrt(xx1.^2 + xx2.^2)), ...
                sin(2 * pi * kappa * sqrt(xx1.^2 + xx2.^2)));
        sval = integral2(s_fun, ...
            -h / 2, h / 2, -h / 2, h / 2) / (h * h);
        k_fun = @(xx, yy) OsSLP2D(xx, yy, kappa, sval);
    elseif dim == 3
        sval = OsSLP3DSelfValue(h, kappa);
        k_fun = @(xx, yy) OsSLP3D(xx, yy, kappa, sval);
    else
        error("ExperimentKernel:UnsupportedDimension", ...
            "OsSLP experiments support dim 2 or 3.");
    end
elseif kernel_type == "Gaussian"
    k_fun = @(xx, yy) Gaussian(xx, yy, sqrt(dim));
else
    error("ExperimentKernel:UnsupportedKernel", ...
        "kernel_type must be SLP, OsSLP, or Gaussian.");
end

end

function sval = OsSLP3DSelfValue(h, kappa)

dist = @(xx1, xx2, xx3) sqrt(xx1.^2 + xx2.^2 + xx3.^2);
s_fun = @(xx1, xx2, xx3) ...
    1 ./ dist(xx1, xx2, xx3) / (4 * pi) ...
    .* complex(...
        cos(2 * pi * kappa * dist(xx1, xx2, xx3)), ...
        sin(2 * pi * kappa * dist(xx1, xx2, xx3)));

sval = 0;
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    -h / 2, 0, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    -h / 2, 0, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    0, h / 2, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    0, h / 2, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    -h / 2, 0, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    -h / 2, 0, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    0, h / 2, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    0, h / 2, ...
    0, h / 2);
sval = sval / h^3;

end

function sval = SLP3DSelfValue(h)

s_fun = @(xx1, xx2, xx3) ...
    1 ./ sqrt((xx1.^2 + xx2.^2 + xx3.^2)) / (4 * pi);

sval = 0;
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    -h / 2, 0, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    -h / 2, 0, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    0, h / 2, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    0, h / 2, ...
    -h / 2, 0);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    -h / 2, 0, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    -h / 2, 0, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    -h / 2, 0, ...
    0, h / 2, ...
    0, h / 2);
sval = sval + integral3(s_fun, ...
    0, h / 2, ...
    0, h / 2, ...
    0, h / 2);
sval = sval / h^3;

end
